name: paisley
version: 0.1.0
description: SPA engine that sends HTML to clients and handles events via WebSocket.
homepage: https://github.com/regiostech/paisley.git
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.0-rc.0
  angel_serialize: ^2.0.0
  html_builder: ^1.0.0
  http_parser: ^3.0.0
  json_god: ^2.0.0-beta
  json_rpc_2: ^2.0.0
  stream_channel: ^1.0.0
  web_socket_channel: ^1.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  test: ^1.0.0
