name: paisley
version: 0.0.0
description: Home-grown server-side SPA framework for Dart.
publish_to: https://pub.regios.dev
author: Tobe O <thosakwe@gmail.com>
dependencies:
  angel_framework: ^2.0.0-rc.0
  json_god: ^2.0.0-beta
  json_rpc_2: ^2.0.0
  stream_channel: ^1.0.0
  web_socket_channel: ^1.0.0
dev_dependencies:
  test: ^1.0.0
